### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by jjcasmar** [morbith-dqtz/agnoc-tools#1]
I am trying to continue your work to add support for Conga 6090 to Valetudo fork, but I am not sure how to start using this tools. Could you a bit more of info please?

**Comment by morbith-dqtz** [comment]
This tools are replacements for the websocket servers where the robot is asking for its configuration and also an implementation of the main parts of the protocol.

ws-8001.js -> This is the first stage of configuration. For get that working you will need to setup your network with a DNS that resolves 3irobotix domain and point that requests to the IP where you run this server. Then when the robot asks for configuration, you will be able to manually configure the addresses where the robot will ask for the other relevant services.

You will need to define the CLOUD variable pointing where you will run the app server.

If you are not planning to use the original phone app the interact with the robot, then you can :

Change the configuration in the robot vía SSH:

/sysConfig.ini and /mnt/UDISK/config/sysConfig.ini server_ssl_enable=1 -> server_ssl_enable=0

And skip using ws-8001.js that require TLS, and use ws-4011.js for this first stage configuration phase.

server-ws.js -> This is the app server, here you will find all the robot protocol features implemented. It's the service where the robot will ask for when receives its  "ws://${cloud}:9090 configuration.

**Comment by jjcasmar** [comment]
Do I still need to run the configuration tools if I have configured my Conga with the official app?

So if I understand correctly, assuming I wont use the official app:

1) Define the CLOUD variable
2) Run ws-4011.js so the robot gets configured
    - Is this configuration destructive? Can I restore to a previous state and use it with the official app if something goes wrong?
3) Run ws-server.js. I tried to use this and I dont undetstand how to send commands to the robot. Do I need to access some webui or something?

**Comment by morbith-dqtz** [comment]
> Do I still need to run the configuration tools if I have configured my Conga with the official app?
> 

Yes, the first configuration step is part of the protocol itself.

> So if I understand correctly, assuming I wont use the official app:
> 
>     1. Define the CLOUD variable
> 
>     2. Run ws-4011.js so the robot gets configured
>        
>        * Is this configuration destructive? Can I restore to a previous state and use it with the official app if something goes wrong?
> 

No, is not destructive. This configuration are not stored, is an ask-reply config step that is fired every time your robot gets started.

>     3. Run ws-server.js. I tried to use this and I dont undetstand how to send commands to the robot. Do I need to access some webui or something?

The server is meant to be a message router between the client and the robot. That Is the server I used to control the robot from the official app. You can use it as "protocol documentation" but there is no client developed, but is easy to write one that talks with this server and passes the control messages to the robot and gets the status messages from the robot.

**Comment by jjcasmar** [comment]
So I use the official app but when using this tools, the official app talks with the server-ws.js which sends the commands to the robot, right?

If I understand correctly, I need to run the ws-4011.js in the robot? How should I do that?

Thanks for the help

**Comment by morbith-dqtz** [comment]
> So I use the official app but when using this tools, the official app talks with the server-ws.js which sends the commands to the robot, right?
> 
Yes. That's it.

> If I understand correctly, I need to run the ws-4011.js in the robot? How should I do that?
>
4011 is the no TLS version of 8001, both do the same. 
You only need to run one of them as configuration dispatcher outside the robot.

**Comment by jjcasmar** [comment]
But how is the robot going to talk to the ws-4011.js in the first place? Do I need to modify the hosts?

**Comment by morbith-dqtz** [comment]
My approach is to use a DNS server in the local network that act as master for 3irobotix.net domain.

I think that is much versatile than use the /etc/hosts approach but both are valid.

**Comment by jjcasmar** [comment]
Fine, I think I now have all the information to test this. 
In the README says the protocol is not complete, is this still the case?
Thanks you very much

**Comment by morbith-dqtz** [comment]
It's pretty sure that some parts are missing, but I use this to program jobs and edit maps  .... For my proposes it's 100% functional.

Maps are the reason I stop my research to port to Valetudo. When I was doing this research I found that the map format was not supported in Valetudo ... my objective was stop using external webservices and with this tools i'm able ... so I stopped at that point.

**Comment by jjcasmar** [comment]
Fair point. 

I want to try to support Valetudo to be able to integrate it in home assistant though, so Ill try to take it from here. 
Thanks
